"""Invoice model tests (AC1, AC2).

Verifies Invoice ORM columns, defaults, constraints against the live DB.

Run:
    docker exec tukijuris-api-1 python -m pytest tests/test_invoice_model.py -v
"""

from __future__ import annotations

import uuid
from decimal import Decimal

import pytest
from sqlalchemy import inspect, text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.config import settings
from app.models.invoice import Invoice


def _engine():
    return create_async_engine(settings.database_url, echo=False)


async def _get_session() -> AsyncSession:
    engine = _engine()
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    return async_session()


async def _real_org_id() -> uuid.UUID:
    """Fetch an existing org id from the DB to satisfy FK constraints."""
    import asyncpg

    db_url = settings.database_url.replace("postgresql+asyncpg://", "postgresql://")
    conn = await asyncpg.connect(db_url)
    try:
        row = await conn.fetchrow("SELECT id FROM organizations LIMIT 1")
        if row is None:
            pytest.skip("No organizations in DB — FK-constrained test skipped")
        return uuid.UUID(str(row["id"]))
    finally:
        await conn.close()


@pytest.mark.integration
class TestInvoiceModel:
    """ORM-level tests for the Invoice model."""

    async def test_invoice_table_name(self):
        assert Invoice.__tablename__ == "invoices"

    async def test_invoice_columns_registered(self):
        """All spec columns must be present in the mapped columns."""
        expected = {
            "id", "org_id", "subscription_id", "provider", "provider_charge_id",
            "status", "currency", "base_amount", "seats_count", "seat_amount",
            "subtotal_amount", "tax_amount", "total_amount", "plan",
            "paid_at", "failed_at", "refunded_at", "voided_at",
            "refund_reason", "void_reason", "provider_event_id",
            "created_at", "updated_at",
        }
        mapper = inspect(Invoice)
        actual = {col.key for col in mapper.mapper.column_attrs}
        missing = expected - actual
        assert not missing, f"Missing mapped columns: {missing}"

    async def test_invoice_defaults(self):
        """Python-side defaults: status=pending, currency=PEN, seats_count=0, seat_amount=0."""
        inv = Invoice(
            org_id=uuid.uuid4(),
            provider="culqi",
            provider_charge_id="chr_test_defaults",
            base_amount=Decimal("70.00"),
            subtotal_amount=Decimal("70.00"),
            tax_amount=Decimal("12.60"),
            total_amount=Decimal("82.60"),
            plan="pro",
        )
        assert inv.status == "pending"
        assert inv.currency == "PEN"
        assert inv.seats_count == 0
        assert inv.seat_amount == 0

    async def test_invoice_id_is_uuid(self):
        inv = Invoice(
            org_id=uuid.uuid4(),
            provider="culqi",
            provider_charge_id="chr_test_id_type",
            base_amount=Decimal("70.00"),
            subtotal_amount=Decimal("70.00"),
            tax_amount=Decimal("12.60"),
            total_amount=Decimal("82.60"),
            plan="pro",
        )
        # id is generated by uuid.uuid4 default
        assert isinstance(inv.id, uuid.UUID)

    async def test_invoice_nullable_fields(self):
        """subscription_id, paid_at, failed_at, refunded_at, voided_at, reasons must accept None."""
        inv = Invoice(
            org_id=uuid.uuid4(),
            provider="mercadopago",
            provider_charge_id="mp_test_nullable",
            base_amount=Decimal("70.00"),
            subtotal_amount=Decimal("70.00"),
            tax_amount=Decimal("12.60"),
            total_amount=Decimal("82.60"),
            plan="pro",
        )
        assert inv.subscription_id is None
        assert inv.paid_at is None
        assert inv.failed_at is None
        assert inv.refunded_at is None
        assert inv.voided_at is None
        assert inv.refund_reason is None
        assert inv.void_reason is None
        assert inv.provider_event_id is None

    async def test_invoice_persists_and_retrieves(self):
        """Round-trip: insert → flush → select → verify fields (AC1)."""
        from sqlalchemy import select

        org_id = await _real_org_id()
        session = await _get_session()
        try:
            charge_id = f"chr_model_test_{uuid.uuid4().hex[:8]}"
            inv = Invoice(
                org_id=org_id,
                provider="culqi",
                provider_charge_id=charge_id,
                status="paid",
                base_amount=Decimal("70.00"),
                seats_count=0,
                seat_amount=Decimal("0.00"),
                subtotal_amount=Decimal("70.00"),
                tax_amount=Decimal("12.60"),
                total_amount=Decimal("82.60"),
                plan="pro",
            )
            session.add(inv)
            await session.flush()

            result = await session.execute(
                select(Invoice).where(Invoice.provider_charge_id == charge_id)
            )
            fetched = result.scalar_one_or_none()
            assert fetched is not None
            assert fetched.status == "paid"
            assert fetched.provider == "culqi"
            assert fetched.plan == "pro"
            assert fetched.currency == "PEN"
        finally:
            await session.rollback()
            await session.close()

    async def test_duplicate_provider_charge_raises(self):
        """Duplicate (provider, provider_charge_id) raises IntegrityError (AC2)."""
        from sqlalchemy.exc import IntegrityError

        org_id = await _real_org_id()
        session = await _get_session()
        try:
            charge_id = f"chr_dup_{uuid.uuid4().hex[:8]}"
            common = dict(
                provider="culqi",
                provider_charge_id=charge_id,
                status="paid",
                base_amount=Decimal("70.00"),
                seat_amount=Decimal("0.00"),
                subtotal_amount=Decimal("70.00"),
                tax_amount=Decimal("12.60"),
                total_amount=Decimal("82.60"),
                plan="pro",
            )
            session.add(Invoice(org_id=org_id, **common))
            await session.flush()

            session.add(Invoice(org_id=org_id, **common))
            with pytest.raises(IntegrityError):
                await session.flush()
        finally:
            await session.rollback()
            await session.close()
